### ISSUE TITLE
Kolla-Build Containers via Jenkins workflow as a Kubernetes Pod

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/openstack-helm#20]
Create a container that can then be used in a Kubernetes/Jenkins workflow. The goal should be:

* Use the existing Jenkins Helm chart to deploy a complete Jenkins system that can be used for building out Kolla containers.
* Add entrypoint logic (again, using Kolla-build --include-footer flags).
* Should be developer initiated into the CI pipeline.
* Make it useable for anyone (create sensible ENV's).

**Comment by v1k0d3n** [comment]
good progress using dind container for kolla-builds. https://github.com/att-comdev/dockerfiles/tree/master/kolla-builder. next step is to determine right way to issue kolla-build to container, and yet make it consumable for anyone else using aic-helm. since this is meant to be deployed as a kubernetes pod manifest, i will create this and the helm chart that will provision this Jenkins CI component.

**Comment by v1k0d3n** [comment]
Linking [dockerfiles/issues/46](https://github.com/att-comdev/dockerfiles/issues/46).

**Comment by alanmeadows** [comment]
Using this issue to start a dialog on the design vision for CI/CD for @v1k0d3n and @nadeemanwar.

First, I think of kolla-builder as a reusable artifact for jenkins kolla builds.  What this means is that its configuration is jenkins driven.  What this means we'll articulate in a moment.

Then there is the trigger perspective: how is this container called and what is driving that? There are two use cases we need to solve for, especially given the plan would be for us to leverage our own git repositories that contain our own custom OpenStack service code but I also think this is a common enterprise use case.  

1) A developer checks a change into git.org.com/openstack/keystone.  In this scenario, we want to test the commit in several ways.  First, likely standard validations occur which include both syntax checks validating for proper end of lines, style requirements, and finally unit tests.  These tests run quickly and catch most errors.  Then we want to actually validate the functionality of the code.  This requires integration tests.  This requires Jenkins to leverage kolla-builder to generate a container for keystone, as well as a container for all other services in the integration test (which likely would require all OpenStack services, and potentially some of our own) from their master branches.  Jenkins will then need to deploy these containers, likely leveraging openstack-helm in a scripted fashion to deploy a complete stack from the ground up, using the newly built Keystone image based on the commit the developer just contributed as well the container images generated for the other services as our latest release for them may not match their master branches as we will always be between releases. Once some basic validation occurs they all enter a Running state, in Kubernetes, jenkins can then trigger simplistic cross service checks and initially this can start with something as simple as tempest, expanding to a few basic rally tests run against the full stack. This will eventually evolve to true integration tests with other AT&T requirements but that is an extension to this open source effort. This is all occurring before the developers change is committed.  This allows a reviewer who could later merge the change to know with full confidence that the change does not break any existing integration tests.  This becomes our gate test for all OpenStack components.

2) At some point, after several of the above scenarios are run through across various OpenStack repositories an AIC release is blessed, repositories are likely tagged--for instance with a release version 1.0.0 in the git repositories where our custom OpenStack code lives, and someone engages a jenkins release pipeline to a specific environment, such as dev, stage, or production or any number of potential environments.  These different environments may imply slightly different workflows, whether those are special tags (here now we are speaking about image tags) to the container images or different publish destinations (more likely).  The underlying workflow is very similar to the above, except this release is manually triggered through a specific release pipeline for each component, with hopefully a parent pipeline that can call them all for convenient "release all" function.  The images produced here are published for long-term _external_ consumption across _multiple repositories_.  Basically containers are built across all OpenStack repositories targeting a specific git tag in our repositories housing the OpenStack component code.  These last two sentences are likely the biggest difference from the first scenario. This also makes sure that our releases are divorced from our merges because although the long-term goal is _continuous delivery_ no enterprise really has the stomach to release a merge across hundreds of production OpenStack deployments.   Eventually this "manual" release functionality may be relegated to only production, while dev and test, do actually receive receive continuous builds once our integration testing reaches a level of trust.

Finally, there is an entirely different scenario and that is jenkins validation of commits to openstack-helm itself.  This does not directly tie into kolla-builder but it should be mentioned here as it will require building and testing.  Commits to this repository should go through a similar but different scenario.  Commits should result in Jenkins running through a similar deploy scenario, leveraging openstack-helm to deploy all charts to an ephemeral namespace, verify they all enter a Running state, and pass some sort of validation test being either tempest or better yet rally.  It will also need its own release pipeline similar to all the above OpenStack services except in this case it will result in the charts being published somewhere as opposed to building a container.  We may instead decide to encapsulate the charts within an "aic-kube" container image at some point to also encapsulate all the tool requirements for helm, such as specific versions of the helm binary, a local tiller, and other services for a reliable and repeatable helm environment deployed into every site.

Lastly, we come to how jenkins is going to accomplish the two scenarios above. This will be a combination of two things, kolla-builder, and jenkins with the kubernetes plugin.  From reading the kubernetes plugin documentation, the foundation of what is offered is the ability to create pods with several containers.  One of those containers acts as a typical Jenkins slave.  There are public images already built for this.  Also within the same pod are our images that are more geared toward building our software, such as kolla-builder.  The fact that they are all part of a single pod means we can share data Jenkins likely has the authorization credentials to fetch, such as all of our internal or public yet private github repositories.  It can then share that data via volumes with other containers.

This likely means that the approach for kolla-builder would be to expect Jenkins to deliver it a kolla-build.conf as a configmap (also supported by the kubernetes plugin) and it will also expect to find the git source for the kolla image its building in a volume mount graciously placed there by the jenkins slave container running in the same pod.  This requires that kolla-builder support a kolla-build.conf configmap. It does not natively support this today, instead supporting several convenient environment variables and an external http reference to an oslo config.  These are great convenience features but we require more flexibility.  Finally, the configmap jenkins injects to the kolla-builder image will likely specify that we wan to build from source but that the source instead of being from a git repository with a specific reference should instead be be from a file path, where jenkins has placed the source code.  This supports the scenario (1) above because note that during integration testing we are not testing an actual merged commit but rather a commit proposed for merging, which at that point jenkins has the best ability to distill into a working checkout placed somewhere for consumption (again using the jenkins slave container->shared volume->kolla-builder along with a crafted kolla-build.conf configmap) by something like kolla-builder.

There is a final complication which I'm sure is a challenge today and really exists whether containers, kubernetes, or kolla-builder is involved and that is validating a change that has an unmerged dependency in another repository - perhaps @nadeemanwar can shed some light on the approach used today to solve for this.  In the scenario (1) above, the commit from the developer change is what we are testing, along with the master branch from every other OpenStack service when our container fleet is built for integration testing.  How will we solve the scenario where a developer needs to commit to the keystone repository to change a fundamental behavior and then wants to follow that up with changes to several other OpenStack services to incorporate support for that change.  This will not fit in our existing scenario as we describe using the master branch from the other repositories to build our containers.  In this example, we need to use unmerged commits as the build foundation to several OpenStack services in order to produce something that forms a valid container fleet for us to test.

In any event, all that said, for the first milestone, I think its fine if we simply target scenario (2) which is required for the demo.  However, as noted it relates heavily to scenario (1) so the long-term vision needs to be kept in mind when developing this first pass.

Let's review how this would look. The flow is something like this.  Let's use the second scenario in our example since this is what we're targeting for the demo.  The first scenario is a nice-to-have.

Jenkins release pipeline is called for keystone.  This is manually triggered as a Jenkins pipeline. It needs some input, such as the git tag to target for the build.  It should already be aware of where the keystone code is located (git://where or https://where for public repositories) as settings in the pipeline itself, since there is a pipeline for each component, and have the authentication means necessary to retrieve it if its not a public git repository it can clone without a key.  Then, jenkins will leverage the kubernetes plugin to create a Pod containing a jenkins slave using any of the standard images to accomplish this.  The pod will also contain a kolla-builder container.  They will have a volume shared between them.  This allows the jenkins slave container in the same pod to retrieve the code the kolla-builder container will need and place it in the shared volume.  The kolla-builder container can then use that retrieved code to build and then publish a kolla container.  Jenkins will have spawned the kolla-builder container with a configmap mounted at /etc/kolla/kolla-build.conf giving it instructions on where to find the source, how to tag the image, and various other build time parameters.

**Comment by v1k0d3n** [comment]
some additional references: https://github.com/kubernetes/helm/issues/1564

**Comment by v1k0d3n** [comment]
Container images are building successfully in a Jenkins pipeline. I will upload current Jenkins config (scrubbed), to a repository for community use soon. All checks, builds, and post-run cleanup tasks are working.

**Comment by v1k0d3n** [comment]
for 0.1.0 release, we're going to break this work into sub-tasks. the first, which this issue will cover will be a jenkins, community-provided pipeline for building containers. this will be uploaded in a [separate repo](https://github.com/att-comdev/aic-ci) potentially later today.

**Comment by v1k0d3n** [comment]
This has been completed for demonstration with refinement coming in further releases.
