### ISSUE TITLE
feat: Finish NodePort assignment for remainder of services

### ISSUE THREAD

**Issue by larryrensing** [att-comdev/openstack-helm#297]
**Is this a bug report or feature request?** (choose one):
Feature request

**Development or Deployment Environment?**:
Both
**Release Tag or Master**:
0.3.0/master

**Expected Behavior**:
Services should have a boolean to expose a NodePort for the service.

**Any Additional Comments**:
A standardized template for how we want to format the values.yaml has been decided [here](https://github.com/att-comdev/openstack-helm/pull/274).  NodePorts for the rest of the OpenStack services other than Heat need to be created.

Applies to the following services: cinder-api, glance-api, keystone-api, neutron-server, nova-metadata, nova-osapi

**Comment by alraddarla** [comment]
I'll take this one.

**Comment by wilreichert** [comment]
I assume the use case for this is an external LB? Would it be possible to implement this in a way so that it's possible to let kubernetes dynamically choose the port from the service port block? Managing sets of ports for every deployed OpenStack environment seems like a lot of manual overhead for an otherwise automated workflow. And chances are whatever you have driving your ingress / LB controller is going to query the service directly making the exact port used irrelevant anyway.

**Comment by intlabs** [comment]
Totally agree with @wilreichert . The only use case I can see for this is when the service is behind an external LB. Considering such an environment is likely to be managed, rather than specifying a "new" port or range to use - why not simply map the default 1:1 with the existing service port? This would mean that in a cluster with a wide service port range (eg 1-65xxx) then the service could just be exposed and 'just work' for development whist allowing an operator to specify the port they actually want to use when doing any real deployment.

**Comment by v1k0d3n** [comment]
yeah @wilreichert, @intlabs and i were talking about this last night, @intlabs i think that what we should really do is discuss this thoroughly and publicly here (so @alraddarla can see/understand the intent), and then make the appropriate changes to what @larryrensing has already submitted. this way, we're modifying the controlled introduction of the concept, throwing it on the wall and taking input from the community, and then continuing with the recommended path you're suggesting. thoughts?

**Comment by wilreichert** [comment]
The biggest differences running kubernetes on metal vs. cloud are persistent storage and network. Storage is a solved issue with with lots of great options, network not so much. The official documented approach is the ingress API yet I don't think I've met a single person who would recommend using it. The design is fine, but the limited feature set and L7 only limitations are rather prohibitive. Search a bit & you'll find a handful of other implementations from the contrib project, HP, openshift, & elsewhere. And pretty much every single project states outright its experimental and to use at your own risk.

Regardless of the implementation you use there's really only 3 basic ways to expose services
1. Reserve the exact ports you will use on your nodes via something like a daemom set & pod proxies to route the traffic to the services.
2. Add node ports to all the services you want to expose & manage the mapping externally with a balancer of some sort.
3. Make the service network routeable and access then directly, no node ports or proxies necessary.

I think it would be prudent to keep all three variations in mind as valid choices for implementations. The one red flag I've thought of regarding #2 above would be if using the CLI tool to do a call something like `openstack image list`. It'll hit the keystone endpoint & get back the glance api node's short DNS name & choke unless you've got both the external port translation and some kind of internal / external DNS mapping implemented. I suppose it could also be mitigated with env variables but we're back to the lots of manual overhead.

Long term I'd love to see a virtual host based ingress solution provided by openstack-helm as a minimal effort out of the box 'just works' solution. Ingress is currently suffering a chicken & egg problem - no uses it because its not considered stable and its not stable because no one is using it. So stop the negative feedback loop & provide a known good solution. If something like https://github.com/kubernetes/ingress/issues/329 would be implemented adding & removing ingress resources with each deploy could be avoided as well.

**Comment by intlabs** [comment]
@wilreichert I've run many OpenStack services behind ingress controllers with some success. This has been using the exact methodology you propose for a long term goal (in my previous Harbor Project), and a quick prototype I made in January with OSH.

Your assessment of the options for exposing K8s services to the world is spot on in my opinion, and this PR should be about addressing option 2 above. Personally, unless you have strong feelings to the contrary I think it should be perfectly possible to proceed using the same port by default for the nodePort that the service uses? My logic behind this is twofold:
 * It prevents us having to take on the burdon of maintaining nodePort mapping that an operator is unlikely to use, whilst also imposing an option upon them.
 * It lets developers enable the nodePort option to perform single replica development work in a really simple and clean fashion.

**Comment by wilreichert** [comment]
Would that work? Node ports are limited to a specific high range, default is 30000 - 32767. Its usually recommended to use port proxies & host ports via a pod if you want 1:1 port mappings. I like the simplicity your plans suggests though.

**Comment by wilkers-steve** [comment]
@wilreichert The node port range is set by a flag on kube-apiserver.  For development, this would work perfectly while allowing operators to specify any value they require for production.

**Comment by wilreichert** [comment]
yep yep.  But now you've added additional configuration constraints on their kubernetes installation, set a bad precedent, and created risk of port conflict for any service not specifically mapped to a port. =)

I'd much rather implement something like [proxy-to-service](https://github.com/kubernetes/contrib/tree/master/for-demos/proxy-to-service). That said, I don't wanna be a roadblock here. If everyone agrees on the NodePort approach please proceed with the appropriate warnings in the documentation.

**Comment by v1k0d3n** [comment]
i do absolutely agree with that point, which is my main hesitation for mapping a 1-to-1 NodePort declaration in our Charts. fact is, it's something that we want to offer, but will recommend and configure otherwise (in favor of a solid ingress implementation). this was the reason for continuing with a simple default NodePort definition, expanding on what @larryrensing had started. i think we can look into the proxy link you provided @wilreichert, but the *original* thought was to provide a NodePort option, and an ingress option, neither of which would *require* changes on the Kube init setup. keep in mind we ask for changes to kube-controller-manager for Ceph, so it wouldn't be out of bounds, but like you I feel this could be a slippery slope.
